version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=assistant
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"

  redis:
    image: redis:latest

  app:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/assistant
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/assistant},
          redis={url=redis://redis:6379}
        }
      - SMTP_HOST=mail.dimuzio.dev
      - SMTP_USERNAME=root
      - SMTP_PASSWORD=
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
